@startuml

actor Péter as Peter
rectangle ElektronikaiWebalkalmazás {
  Peter --> (Bejelentkezés)
  Peter --> (Termékkeresés)
  Peter --> (Termék kiválasztása)
  Peter --> (Kosárba helyezés)
  Peter --> (Kosár ellenőrzése)
  Peter --> (Pénztár oldal)
  Peter --> (Rendelés megerősítése)
  (Rendelés megerősítése) --> Peter : Email visszaigazolás
}

@enduml

![order-use-case](use-case.png)
